In [12]:
import pandas as pd
from sklearn import preprocessing
from sklearn.preprocessing import Binarizer,LabelBinarizer

In [13]:
data = pd.read_csv('../datasets/WA_Fn-UseC_-Sales-Win-Loss.csv')

Binarize labels in a one-vs-all fashion

Several regression and binary classification algorithms are available in scikit-learn. A simple way to extend these algorithms to the multi-class classification case is to use the so-called one-vs-all scheme.

At learning time, this simply consists in learning one regressor or binary classifier per class. In doing so, one needs to convert multi-class labels to binary labels (belong or does not belong to the class). LabelBinarizer makes this process easy with the transform method.

At prediction time, one assigns the class for which the corresponding model gave the greatest confidence. LabelBinarizer makes this easy with the inverse_transform method.

In [14]:
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
0,1641984,Accessories,Car,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1
1,1658010,Accessories,Car,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1
2,1674737,Motorcycle Parts,Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1
3,1675224,Shelters,Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1
4,1689785,Accessories,Car,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4

In [15]:
data.tail()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category
78020,10089932,Batteries,Car,Southeast,Reseller,0,Loss,2,0,0,250000,1,1,3,Unknown,0.0,0.0,0.0,6
78021,10089961,Shelters,Non-auto,Northeast,Reseller,0,Won,1,0,0,180000,1,1,0,Unknown,0.0,0.0,0.0,5
78022,10090145,Accessories,Car,Southeast,Reseller,0,Loss,2,0,0,90000,1,1,0,Unknown,0.0,0.0,0.0,4
78023,10090430,Accessories,Car,Southeast,Fields Sales,0,Loss,2,0,0,120000,1,1,0,Unknown,1.0,0.0,0.0,5
78024,10094255,InteriorAccessories,Car,Mid-Atlantic,Reseller,0,Loss,1,0,0,90000,1,1,0,Unknown,0.0,0.0,0.0,4

In [16]:
data.groupby('Opportunity Result').size()

Opportunity Result
Loss    60398
Won     17627
dtype: int64

In [17]:
lb = LabelBinarizer()

In [18]:
data['result'] = lb.fit_transform(data['Opportunity Result'])

In [19]:
data.head()

,Opportunity Number,Supplies Subgroup,Supplies Group,Region,Route To Market,Elapsed Days In Sales Stage,Opportunity Result,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Competitor Type,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category,result
0,1641984,Accessories,Car,Northwest,Fields Sales,76,Won,13,104,101,0,5,5,0,Unknown,0.69636,0.113985,0.154215,1,1
1,1658010,Accessories,Car,Pacific,Reseller,63,Loss,2,163,163,0,3,5,0,Unknown,0.00000,1.000000,0.000000,1,0
2,1674737,Motorcycle Parts,Non-auto,Pacific,Reseller,24,Won,7,82,82,7750,1,1,0,Unknown,1.00000,0.000000,0.000000,1,1
3,1675224,Shelters,Non-auto,Midwest,Reseller,16,Loss,5,124,124,0,1,1,0,Known,1.00000,0.000000,0.000000,1,0
4,1689785,Accessories,Car,Pacific,Reseller,69,Loss,11,91,13,69756,1,1,0,Unknown,0.00000,0.141125,0.000000,4,0

In [20]:
data.groupby('result').size()

result
0    60398
1    17627
dtype: int64

## with thresholding

In [21]:
data.describe()

,Opportunity Number,Elapsed Days In Sales Stage,Sales Stage Change Count,Total Days Identified Through Closing,Total Days Identified Through Qualified,Opportunity Amount USD,Client Size By Revenue,Client Size By Employee Count,Revenue From Client Past Two Years,Ratio Days Identified To Total Days,Ratio Days Validated To Total Days,Ratio Days Qualified To Total Days,Deal Size Category,result
count,7.802500e+04,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000,78025.000000
mean,7.653429e+06,43.595348,2.955732,16.728356,16.314348,91637.260750,1.620481,1.604050,0.303287,0.203063,0.488314,0.185048,3.436745,0.225915
std,1.054848e+06,26.585600,1.497242,16.729593,16.562597,133161.029157,1.235796,1.210744,0.930290,0.364985,0.448077,0.340283,1.656890,0.418186
min,1.641984e+06,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000
25%,6.900423e+06,19.000000,2.000000,4.000000,4.000000,15000.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000
50%,7.545569e+06,43.000000,3.000000,12.000000,12.000000,49000.000000,1.000000,1.000000,0.000000,0.000000,0.448000,0.000000,3.000000,0.000000
75%,8.228329e+06,65.000000,3.000000,24.000000,24.000000,105099.000000,1.000000,1.000000,0.000000,0.197225,1.000000,0.188552,5.000000,0.000000
max,1.009427e+07,210.000000,23.000000,208.000000,208.000000,1000000.000000,5.000000,5.000000,4.000000,1.000000,1.000000,1.000000,7.000000,1.000000

In [25]:
binarizer_elapsedDays = Binarizer(threshold=65)
binarizer_ratioDaysIden = Binarizer(threshold=0.19)

In [26]:
elapsedDays = data['Elapsed Days In Sales Stage'].values.reshape(1, -1) 
ratioDaysIden = data['Ratio Days Identified To Total Days'].values.reshape(1, -1)

In [27]:
elapsed_days_binary = binarizer_elapsedDays.fit_transform(elapsedDays)
ratio_days_identified_binary = binarizer_ratioDaysIden.fit_transform(ratioDaysIden)

In [28]:
print ("\nOriginal elapsed days data values : \n",  elapsedDays) 
print ("\nOriginal 'Ratio Days Identified To Total Days' data values : \n",  ratioDaysIden) 
print ("\nBinarized elapsed days : \n", elapsed_days_binary) 
print ("\nBinarized 'Ratio Days Identified To Total Days' : \n", ratio_days_identified_binary)

Original elapsed days data values :
 [[76 63 24 ...  0  0  0]]

Original 'Ratio Days Identified To Total Days' data values :
 [[0.69636 0.      1.      ... 0.      1.      0.     ]]

Binarized elapsed days :
 [[1 0 0 ... 0 0 0]]

Binarized 'Ratio Days Identified To Total Days' :
 [[1. 0. 1. ... 0. 1. 0.]]